cargo-features = ["panic-immediate-abort"]

[workspace]
resolver = "2"
members = ["xtask", "kernel", "config", "crates/hal", "crates/drivers", "crates/net", "crates/pgp-lite", "crates/pkg", "crates/ext4w", "crates/disk", "crates/initrd", "crates/usb", "crates/imobiledevice", "crates/usbnet", "tiny-init", "kstub"]

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
panic = "abort"

[profile.small]
inherits = "release"
panic = "immediate-abort"
