[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
bootinfo = { path = "../crates/bootinfo" }
hostcfg = { path = "../crates/hostcfg" }
sha2 = "0.11"
miniz_oxide = "0.9"
serde = "1"
pgp-lite = { path = "../crates/pgp-lite", features = ["std"] }
ext4w = { path = "../crates/ext4w" }
initrd = { path = "../crates/initrd" }
pkg = { path = "../crates/pkg" }
