[package]
name = "imobiledevice"
version = "0.1.0"
edition = "2021"

[dependencies]
usb = { path = "../usb" }
hal = { path = "../hal" }
drivers = { path = "../drivers", default-features = false }
pgp-lite = { path = "../pgp-lite" }
rsa = { version = "0.9", default-features = false }
rand_core = { version = "0.6", default-features = false }
getrandom = { version = "0.2", features = ["custom"] }
sha2 = { version = "0.10", default-features = false, features = ["force-soft"] }

[features]
std = ["rsa/std"]

[dev-dependencies]
imobiledevice = { path = ".", features = ["std"] }
