//! Writes a config as readable, deterministic Lua in the `as` layout. The output loads back with [`crate::lua::load`]
//! to the same configuration; field order and list order are fixed, and passwords appear only as hashes.
use crate::asconfig::AsConfig;
use crate::host::HostConfig;
use config::Config;
use std::fmt::Write;

/// First line of every generated file; the GUI edits only files that carry it structurally.
pub const HEADER: &str = "-- generated by archstaller-gui";

/// A Lua double-quoted string literal.
pub fn lua_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 || c as u32 == 0x7f => write!(out, "\\{:03}", c as u32).unwrap(),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

fn list<'a>(items: impl IntoIterator<Item = &'a String>) -> String {
    let v: Vec<String> = items.into_iter().map(|s| lua_str(s)).collect();
    if v.is_empty() {
        "{}".into()
    } else {
        format!("{{ {} }}", v.join(", "))
    }
}

fn opt(name: &str, v: &Option<String>) -> Option<String> {
    v.as_ref().map(|s| format!("{name} = {}", lua_str(s)))
}

/// The `aur = { ... }` field of `as.packages` for these packages, indented to sit inside it (empty
/// string when there are none).
pub fn aur_block(aur: &[config::AurPackage]) -> String {
    let mut o = String::new();
    if aur.is_empty() {
        return o;
    }
    writeln!(o, "    -- Built on the installed system at its first boot, from the pinned and reviewed recipe.").unwrap();
    writeln!(o, "    aur = {{").unwrap();
    for a in aur {
        let mut f = vec![format!("name = {}", lua_str(&a.name)), format!("pkgbase = {}", lua_str(&a.pkgbase)), format!("commit = {}", lua_str(&a.commit)), format!("sha256 = {}", lua_str(&a.sha256))];
        if a.vcs {
            f.push("vcs = true".into());
        }
        if a.as_dep {
            f.push("as_dep = true".into());
        }
        if !a.deps.is_empty() {
            f.push(format!("deps = {}", list(&a.deps)));
        }
        if !a.build_deps.is_empty() {
            f.push(format!("build_deps = {}", list(&a.build_deps)));
        }
        if !a.services.is_empty() {
            f.push(format!("services = {}", list(&a.services)));
        }
        writeln!(o, "      {{ {} }},", f.join(", ")).unwrap();
    }
    writeln!(o, "    }},").unwrap();
    o
}

const KEYWORDS: &[&str] = &["and", "break", "do", "else", "elseif", "end", "false", "for", "function", "goto", "if", "in", "local", "nil", "not", "or", "repeat", "return", "then", "true", "until", "while"];

/// A table key: bare when it is a Lua name, `["..."]` otherwise.
fn key(k: &str) -> String {
    let bare = k.chars().next().is_some_and(|c| c.is_ascii_alphabetic() || c == '_') && k.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') && !KEYWORDS.contains(&k);
    if bare {
        k.to_string()
    } else {
        format!("[{}]", lua_str(k))
    }
}

/// Renders the config as `return { as = ... }`. `Script::content` is never written (it is filled in
/// at build time); providers are written sorted by dependency name.
pub fn to_lua(cfg: &Config, host: &HostConfig) -> String {
    let a = AsConfig::from_parts(cfg, host);
    let mut o = String::new();
    writeln!(o, "{HEADER}").unwrap();
    writeln!(o, "-- Plain Lua: edit it by hand or with the GUI. Password hashes only, never plaintext.").unwrap();
    writeln!(o, "---@type AsConfig").unwrap();
    writeln!(o, "local as = {{").unwrap();
    writeln!(o, "  schema = {},", a.schema).unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  system = {{").unwrap();
    writeln!(o, "    hostname = {},", lua_str(&a.system.hostname)).unwrap();
    writeln!(o, "    timezone = {},", lua_str(&a.system.timezone)).unwrap();
    writeln!(o, "    locale = {},", lua_str(&a.system.locale)).unwrap();
    writeln!(o, "    keymap = {},", lua_str(&a.system.keymap)).unwrap();
    if let Some(h) = &a.system.root_password_hash {
        writeln!(o, "    root_password_hash = {},", lua_str(h)).unwrap();
    }
    writeln!(o, "  }},").unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  install = {{").unwrap();
    writeln!(o, "    disk = {{").unwrap();
    if let Some(m) = &a.install.disk.model {
        writeln!(o, "      model = {},", lua_str(m)).unwrap();
    }
    if !a.install.disk.confirm_serial.is_empty() {
        writeln!(o, "      confirm_serial = {},", lua_str(&a.install.disk.confirm_serial)).unwrap();
    }
    if a.install.disk.auto_largest {
        writeln!(o, "      -- WARNING: erases and installs onto the LARGEST disk, without asking.").unwrap();
    }
    writeln!(o, "      auto_largest = {},", a.install.disk.auto_largest).unwrap();
    writeln!(o, "      esp_mib = {},", a.install.disk.esp_mib).unwrap();
    writeln!(o, "    }},").unwrap();
    writeln!(o, "    mirrors = {},", list(&a.install.mirrors)).unwrap();
    if a.install.dry_run {
        writeln!(o, "    dry_run = true,").unwrap();
    }
    writeln!(o, "  }},").unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  packages = {{").unwrap();
    writeln!(o, "    explicit = {},", list(&a.packages.explicit)).unwrap();
    let providers: Vec<String> = a.packages.providers.iter().map(|(k, v)| format!("{} = {}", key(k), lua_str(v))).collect();
    writeln!(o, "    providers = {{ {} }},", providers.join(", ")).unwrap();
    o.push_str(&aur_block(&cfg.aur));
    writeln!(o, "  }},").unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  users = {{").unwrap();
    for u in &a.users {
        writeln!(o, "    {{ name = {}, password_hash = {}, groups = {}, shell = {} }},", lua_str(&u.name), lua_str(&u.password_hash), list(&u.groups), lua_str(&u.shell)).unwrap();
    }
    writeln!(o, "  }},").unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  first_boot = {{").unwrap();
    writeln!(o, "    services = {},", list(&a.first_boot.services)).unwrap();
    writeln!(o, "    kernel_params = {},", list(&a.first_boot.kernel_params)).unwrap();
    if !a.first_boot.user_files.is_empty() {
        writeln!(o, "    user_files = {{").unwrap();
        for f in &a.first_boot.user_files {
            writeln!(o, "      {{ url = {}, dest = {} }},", lua_str(&f.url), lua_str(&f.dest)).unwrap();
        }
        writeln!(o, "    }},").unwrap();
    }
    if !a.first_boot.user_archives.is_empty() {
        writeln!(o, "    user_archives = {{").unwrap();
        for f in &a.first_boot.user_archives {
            writeln!(o, "      {{ url = {} }},", lua_str(&f.url)).unwrap();
        }
        writeln!(o, "    }},").unwrap();
    }
    if !a.first_boot.scripts.is_empty() {
        writeln!(o, "    -- Run as root at the end of the first boot, in this order.").unwrap();
        writeln!(o, "    scripts = {{").unwrap();
        for s in &a.first_boot.scripts {
            let mut f = vec![format!("id = {}", lua_str(&s.id))];
            if !s.args.is_empty() {
                f.push(format!("args = {}", list(&s.args)));
            }
            f.extend(opt("file", &s.file));
            f.extend(opt("url", &s.url));
            f.extend(opt("sha256", &s.sha256));
            writeln!(o, "      {{ {} }},", f.join(", ")).unwrap();
        }
        writeln!(o, "    }},").unwrap();
    }
    writeln!(o, "  }},").unwrap();
    writeln!(o).unwrap();

    writeln!(o, "  -- Build-host settings (not part of what the installer receives).").unwrap();
    writeln!(o, "  build = {{").unwrap();
    if let Some(p) = &a.build.profile {
        writeln!(o, "    profile = {},", lua_str(p)).unwrap();
    }
    writeln!(o, "    tethering = {},", a.build.tethering).unwrap();
    if let Some(d) = &a.build.installer_drivers {
        writeln!(o, "    installer_drivers = {},", list(d)).unwrap();
    }
    writeln!(o, "  }},").unwrap();
    writeln!(o, "}}").unwrap();
    writeln!(o).unwrap();
    writeln!(o, "return {{ as = as }}").unwrap();
    o
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::host::Build;

    fn full() -> (Config, HostConfig) {
        let mut c = crate::lua::tests_support::minimal_config();
        c.hostname = "my-box".into();
        c.disk = config::Disk { model: Some("Samsung".into()), confirm_serial: "S1\"2".into(), auto_largest: false, esp_mib: 1024 };
        c.packages = vec!["base".into(), "linux".into(), "grub".into()];
        c.providers = vec![("initramfs".into(), "mkinitcpio".into())];
        c.root_password_hash = Some("$6$salt$abcdefghijklmnopqrstuvwxyz./".into());
        c.users = vec![config::User { name: "arch".into(), password_hash: "$6$salt$abcdefghijklmnopqrstuvwxyz./".into(), groups: vec!["wheel".into()], shell: "/bin/bash".into() }];
        c.services = vec!["systemd-networkd.service".into()];
        c.aur = vec![config::AurPackage {
            name: "zen-browser-bin".into(),
            pkgbase: "zen-browser-bin".into(),
            commit: "a".repeat(40),
            sha256: "b".repeat(64),
            vcs: false,
            as_dep: false,
            deps: vec!["gtk3".into(), "base-devel".into()],
            build_deps: vec!["base-devel".into()],
            services: vec!["zen.service".into()],
        }];
        c.kernel_params = vec!["quiet".into()];
        c.user_files = vec![config::UserFile { url: "https://e.org/a.lua".into(), dest: ".config/a.lua".into() }];
        c.user_archives = vec![config::UserArchive { url: "https://e.org/c.zip".into() }];
        c.scripts = vec![
            config::Script { id: "enable-sshd".into(), ..Default::default() },
            config::Script { id: "mine".into(), file: Some("scripts/mine.sh".into()), args: vec!["--fast".into()], ..Default::default() },
            config::Script { id: "remote".into(), url: Some("https://e.org/r.sh".into()), sha256: Some("b".repeat(64)), ..Default::default() },
        ];
        let h = HostConfig {
            build: Build { profile: Some("large".into()), tethering: true },
            installer_drivers: Some(vec!["virtio-blk".into(), "virtio-net".into()]),
        };
        (c, h)
    }

    #[test]
    fn escapes_strings() {
        assert_eq!(lua_str("a\"b\\c\nd\u{1}"), "\"a\\\"b\\\\c\\nd\\001\"");
    }

    #[test]
    fn round_trips_through_the_loader() {
        let (c, h) = full();
        let text = to_lua(&c, &h);
        assert!(text.starts_with(HEADER));
        let dir = std::env::temp_dir().join(format!("hostcfg-writer-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("c.lua");
        std::fs::write(&path, &text).unwrap();
        let back = crate::lua::load(&path).unwrap();
        assert_eq!(format!("{:?}", back.config), format!("{c:?}"));
        assert_eq!(back.host, h);
        // Deterministic: writing the loaded config gives the same text.
        assert_eq!(to_lua(&back.config, &back.host), text);
        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn minimal_config_round_trips() {
        let c = crate::lua::tests_support::minimal_config();
        let h = HostConfig::default();
        let dir = std::env::temp_dir().join(format!("hostcfg-writer-min-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("c.lua");
        std::fs::write(&path, to_lua(&c, &h)).unwrap();
        let back = crate::lua::load(&path).unwrap();
        assert_eq!(format!("{:?}", back.config), format!("{c:?}"));
        let _ = std::fs::remove_dir_all(&dir);
    }
}
