[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
config = { path = "../config" }
hal = { path = "../crates/hal" }
drivers = { path = "../crates/drivers" }
limine = "0.6"
talc = "5"
spinning_top = "0.3"
postcard = { version = "1", default-features = false, features = ["alloc"] }

[features]
fault-test = []
disk-selftest = []
net-selftest = []
